import streamlit as st
import smtplib
from email.mime.text import MIMEText
from datetime import datetime
from navbar import show_navbar
from theme import load_theme

st.set_page_config(layout="wide")

load_theme()
show_navbar()

st.title("📧 Email Reports")

if not st.session_state.get("logged_in", False):
    st.switch_page("pages/0_Login.py")
    st.stop()

recipient = st.text_input(
    "Recipient Email"
)

if st.button(
    "📤 Send Business Report",
    use_container_width=True
):

    try:

        df = st.session_state.get("data")

        total_customers = len(df)

        churn_rate = 0

        if "Churned" in df.columns:
            churn_rate = round(
                df["Churned"].mean() * 100,
                2
            )

        revenue = 0

        if "Lifetime_Value" in df.columns:
            revenue = round(
                df["Lifetime_Value"].sum(),
                2
            )

        report = f"""
SaaS Business Analytics Report

Generated:
{datetime.now()}

Total Customers:
{total_customers}

Churn Rate:
{churn_rate}%

Revenue:
₹{revenue:,.2f}

Generated by SaaS Business Analytics Platform
"""

        msg = MIMEText(report)

        msg["Subject"] = (
            "SaaS Analytics Report"
        )

        msg["From"] = st.secrets[
            "EMAIL_USER"
        ]

        msg["To"] = recipient

        server = smtplib.SMTP(
            "smtp.gmail.com",
            587
        )

        server.starttls()

        server.login(
            st.secrets["EMAIL_USER"],
            st.secrets["EMAIL_PASSWORD"]
        )

        server.send_message(msg)

        server.quit()

        st.success(
            "Report Sent Successfully!"
        )

    except Exception as e:

        st.error(
            f"Error: {e}"
        )